# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 04:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20170816_0422'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='variant',
            new_name='trim',
        ),
    ]
